spring:
  datasource:
    url: ${DBMS_CONNECTION}
    driverClassname: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds