spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_learn?useSSL=false&allowPublicKeyRetrieval=true
    driverClassname: com.mysql.cj.jdbc.Driver
    username: root
    password: 170804
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  signerKey: "RIDdDrZ4IzV5zpP1zc7lSqhR71AWXxXTjZnYqov5TAyoz8wHHp+mOr0eg94WwxCk"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds